// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6yHP3FIR-pKozm_yGOTyHAok8vF0GPCA',
    appId: '1:701530927205:web:YOUR_WEB_APP_ID',
    messagingSenderId: '701530927205',
    projectId: 'trego-fb4f3',
    authDomain: 'trego-fb4f3.firebaseapp.com',
    storageBucket: 'trego-fb4f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yHP3FIR-pKozm_yGOTyHAok8vF0GPCA',
    appId: '1:701530927205:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '701530927205',
    projectId: 'trego-fb4f3',
    storageBucket: 'trego-fb4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6yHP3FIR-pKozm_yGOTyHAok8vF0GPCA',
    appId: '1:701530927205:ios:5dfe32887f746e5c4d168c',
    messagingSenderId: '701530927205',
    projectId: 'trego-fb4f3',
    storageBucket: 'trego-fb4f3.firebasestorage.app',
    iosBundleId: 'com.health.trego',
    iosClientId: '701530927205-rp18lnlenfco7q1qfu7ah0dq0cerug4t.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6yHP3FIR-pKozm_yGOTyHAok8vF0GPCA',
    appId: '1:701530927205:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '701530927205',
    projectId: 'trego-fb4f3',
    storageBucket: 'trego-fb4f3.firebasestorage.app',
    iosBundleId: 'com.health.trego',
  );
} 